import Head from 'next/head'
import { GetServerSideProps } from 'next'
import { getProducts } from '../lib/products'
import { Product } from '@prisma/client'
import { CaretDown, CaretUp, MagnifyingGlass, Plus } from 'phosphor-react'
import Image from 'next/image'
import mercado from '../assets/mercadolivre.webp'

type ProductsProps = {
  products: Product[]
}

export default function Home({ products }: ProductsProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container bg-zinc-50'>
        <header className='p-4 bg-zinc-100'>
          <div className='flex items-center justify-between'>

            <h1 className='font-bold text-3xl p-2'>BellWell</h1>

            <button className='flex items-center gap-1 h-10 p-2 text-sm font-bold border-2 border-slate-900 rounded-lg'>
              <Plus size={20} />
              Novo Item
            </button>

          </div>
          <div className="w-full my-4">
            <form>
              <div className="flex">
                <select defaultValue={0} className="py-1 px-1 text-sm font-medium text-gray-900 bg-gray-50 rounded-l-xl border border-gray-300 ">
                  <option selected value={0}>Comodos</option>
                  <option value="US">Quarto</option>
                  <option value="CA">Sala</option>
                  <option value="FR">Cozinha</option>
                  <option value="DE">Banheiro</option>
                </select>
                <div className="relative w-full">
                  <input
                    type="search"
                    className="block p-2.5 w-full z-20 text-sm text-gray-900 bg-gray-50 rounded-r-xl border-l-gray-50 border-l-2 border border-gray-300 focus:ring-blue-500 focus:border-blue-500"
                    placeholder="Procurar produtos..."
                  />
                  <button
                    type="submit"
                    className="absolute top-0 right-0 p-2.5 text-sm font-medium text-white bg-emerald-600 rounded-r-xl border border-gray-300 focus:outline-none">
                    <MagnifyingGlass className='w-5 h-5' />
                    <span className="sr-only">Search</span>
                  </button>
                </div>
              </div>
            </form>
          </div>
        </header>

        <main className='grid grid-cols-12 gap-3 mt-5'>

          {products.map(product => {
            return (
              <div key={product.id} className='col-span-12 flex justify-center'>
                <div className='w-[80%] border border-gray-200 rounded-lg shadow p-2'>
                  <img src={product.image_url} alt={`Imagem do produto ${product.name}`} className='shadow-lg' />

                  <h3 className='font-bold text-lg mt-4'>{product.name}</h3>

                  <p className='font-light text-sm'>Este item pode ser adquirido no {product.description}</p>
                  <div className='w-full text-center my-4 '>
                    <a href={product.link} rel="noopener noreferrer" target="_blank" className='bg-emerald-600 h-10 p-2 rounded-lg text-white'>Compre Agora</a>
                  </div>
                </div>
              </div>
            )
          })}
        </main>
      </div >

    </>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const products = await getProducts()

  return {
    props: {
      products
    }
  }
}